version: 2
builds:
  - id: 'connect'
    binary: connect
    dir: ./go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - name_template: >-
      connect_{{ .Version }}_
      {{- if eq .Os "darwin" }}mac_
      {{- else if eq .Os "linux" }}linux_
      {{- else if eq .Os "windows" }}win_{{end}}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "amd64_v1" }}x86_64
      {{- else }}{{ .Arch }}{{end}}
    formats: gz
    files:
      - none*
checksum:
  name_template: 'connect.checksum'
snapshot:
  version_template: "{{ .Tag }}-snapshot"
changelog:
  disable: true
release:
  prerelease: auto
