name: 'DA Probes'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  profiler:
    name: 'Update Probes Data'
    runs-on: ubuntu-latest
    steps:
      - name: Install pcap
        run: sudo apt-get install -y libpcap-dev

      - name: Clone Profile Data
        run: git clone https://github.com/unblocked-web/browser-profile-data.git
        working-directory: ..

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
          submodules: 'true'

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Yarn build
        run: yarn build

      - name: Sync Path Patterns
        working-directory: ./double-agent
        run: yarn workspace @double-agent/config sync

      - name: Import Profiles
        run: yarn workspace @unblocked-web/double-agent-stacks 0

      - name: Create Probes
        run: yarn workspace @unblocked-web/double-agent-stacks 1

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: probe-data-checkin
        with:
          repository: ./double-agent/probe-data
          branch: main
          commit_message: "chore: automatic probe data"

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.probe-data-checkin.outputs.changes_detected == 'true'
        with:
          branch: main
          commit_message: "chore(probes): point at new double agent"
