name: Test Matrix

on:
  push:
    branches:
      - '*'
      - '!gh-pages'
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Test Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [14, 16]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install pcap
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install -y libpcap-dev

      - name: Chocolatey Install Action
        if: ${{ matrix.os == 'windows-latest' }}
        uses: crazy-max/ghaction-chocolatey@v1.4.2
        with:
          args: install python2 visualcpp-build-tools -y

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        if: ${{ matrix.os == 'windows-latest' }}
        
      - name: Yarn build
        run: yarn build:all

      - name: Linux - Apt Install Chrome(s)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: ./build
        run: sudo $(npx install-browser-deps)

      - name: Run Lint
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node-version == 14 }}
        run: NODE_OPTIONS=--max-old-space-size=4096 yarn lint

      - name: Run tests
        run: yarn test:all --testTimeout=60000 --maxWorkers=2

      - name: 'Tar files'
        if: ${{ failure() }}
        run: tar -cvf test-logs.tar .data-test

      - name: Upload Databases
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-logs-${{matrix.os}}-${{ matrix.node-version }}
          path: test-logs.tar
          retention-days: 1
