name: 'Local Doms'

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 9 * * *'

jobs:
  docker-doms:
    name: 'Docker DOMs'
    runs-on: ubuntu-latest
    steps:
      - name: Install pcap
        run: sudo apt-get install -y libpcap-dev

      - uses: actions/checkout@v3
        with:
          ref: main
          repository: unblocked-web/browser-profile-data
          path: browser-profiler-data

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          submodules: 'true'
          path: unblocked

      - name: Install unblocked
        run: yarn build
        working-directory: ./unblocked

      - name: 'Collect Local Doms'
        run: yarn workspace @unblocked-web/browser-profiler profile:dom-local
        working-directory: ./unblocked
        env:
          NODE_ENV: development
          RUN_DOCKERS: true
          RUN_LOCAL: false

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ always() }}
        with:
          branch: main
          repository: ./browser-profiler-data
          commit_message: 'chore(local-doms): automatic updates'
