name: 'Check for new profiles'

on:
  workflow_dispatch:
    inputs:
      clearPlugins:
        description: 'Redo any plugin-ids (comma separated)'
        required: false
  schedule:
    - cron: '0 7 * * *'

jobs:
  profiler:
    name: 'Update Agents & Stats'
    runs-on: ubuntu-latest
    steps:
      - name: Install pcap
        run: sudo apt-get install -y libpcap-dev

      - uses: actions/checkout@v3
        with:
          ref: main
          repository: unblocked-web/browser-profile-data
          path: browser-profiler-data

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          submodules: 'true'
          path: unblocked

      - name: Install unblocked
        run: yarn build:all
        working-directory: ./unblocked

      - name: 'Clear plugin-ids from manual'
        if: ${{ github.event.inputs.clearPlugins }}
        run: yarn workspace @unblocked-web/browser-profiler profile:clean ${{ github.event.inputs.clearPlugins }}
        working-directory: ./unblocked

      - name: 'Collect new Browserstack Profiles'
        run: yarn workspace @unblocked-web/browser-profiler profile:browserstack
        working-directory: ./unblocked
        env:
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ always() }}
        with:
          branch: main
          repository: ./browser-profiler-data
          commit_message: "chore(profiles): automatic updates"
