name: 'Profile:DOM'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  doms:
    name: 'Update Profiled Doms'
    runs-on: ubuntu-latest
    steps:
      - name: Install pcap
        run: sudo apt-get install -y libpcap-dev

      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.PAT }}
          repository: unblocked-web/browser-profile-data
          path: browser-profile-data

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          submodules: 'recursive'
          path: unblocked

      - name: Install unblocked
        run: yarn build
        working-directory: ./unblocked

      - name: 'Collect new Browserstack Profiles'
        run: yarn workspace @unblocked-web/browser-profiler profile:dom-browserstack
        working-directory: ./unblocked
        env:
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'Collect Local Doms'
        run: yarn workspace @unblocked-web/browser-profiler profile:dom-local
        working-directory: ./unblocked
        env:
          NODE_ENV: development
          RUN_DOCKERS: true
          RUN_LOCAL: false

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ always() }}
        with:
          branch: main
          repository: ./browser-profile-data
          commit_message: 'chore(profiled-doms): automatic updates'
