name: 'Update User Agents & Stats'

on:
  workflow_dispatch:
  schedule:
    # Run at 10pm daily
    - cron: '0 20 * * *'
jobs:
  useragents:
    name: 'Update Agents & Stats'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Yarn build
        run: yarn build

      - name: Linux - Apt Install Chrome(s)
        run: sudo $(npx install-browser-deps)

      - name: 'Collect new Browserstack User Agents'
        run: yarn update:agents
        working-directory: real-user-agents
        env:
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'Update Stats'
        run: yarn update
        working-directory: real-user-agents

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(stats): automatic updates"
