name: 'Publish a built Javascript Branch'

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Javascript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Build modules
        run: yarn && yarn build:dist --network-timeout 1000000

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build Sockets
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v1.23.0
          args: build --clean --skip=validate --snapshot
          workdir: ${{ github.workspace }}/agent/mitm-socket

      - name: Copy built files
        run: |
          mkdir -p build-dist/agent/mitm-socket/dist
          cp -r agent/mitm-socket/dist/* build-dist/agent/mitm-socket/dist
        shell: bash

      - name: Publish branch
        run: |
          cd build-dist
          git config --global user.email "staff@ulixee.org"
          git config --global user.name "CI"
          git init -b main
          git add agent/mitm-socket/dist/** -f
          git add plugins/default-browser-emulator/data/** -f
          git add -A
          git commit -m 'Auto-build Javascript files'
          git push -f https://ulixee:${{ env.GH_TOKEN }}@github.com/ulixee/hero.git main:${{ github.ref_name }}-built-js
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
