name: 'Profile:DOM'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  doms:
    name: 'Update Profiled Doms'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Install pcap
        run: sudo apt-get install -y libpcap-dev

      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PAT }}
          repository: ulixee/browser-profile-data
          path: browser-profile-data

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          submodules: 'true'
          path: hero

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: hero/yarn.lock

      - name: Install hero
        run: yarn build:simple
        working-directory: ./hero

      - name: 'Collect new Browserstack Profiles'
        run: yarn workspace @ulixee/hero-browser-profiler profile:dom-browserstack
        working-directory: ./hero
        env:
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'Collect Local Doms'
        run: yarn workspace @ulixee/hero-browser-profiler profile:dom-local
        working-directory: ./hero
        env:
          NODE_ENV: development
          RUN_DOCKERS: true
          RUN_LOCAL: false

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ always() }}
        with:
          branch: main
          repository: ./browser-profile-data
          commit_message: 'chore(profiled-doms): automatic updates'
